export let CarpenterServices = {
    service_id: "13",
    service_name: "Carpenter Services",
    description: "Expert carpentry services for all your woodworking needs.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Furniture Repair",
        description: "Repair and restoration of furniture.",
        price: 80,
        currency: "USD",
        image_url: "https://example.com/furniture-repair.jpg",
      },
      {
        service_id: "102",
        service_name: "Custom Furniture",
        description: "Creation of custom-made furniture.",
        price: 200,
        currency: "USD",
        image_url: "https://example.com/custom-furniture.jpg",
      },
      {
        service_id: "103",
        service_name: "Cabinetry",
        description: "Design and installation of cabinets.",
        price: 150,
        currency: "USD",
        image_url: "https://example.com/cabinetry.jpg",
      },
      {
        service_id: "201",
        service_name: "Door and Window Repair",
        description: "Repair and installation of doors and windows.",
        price: 100,
        currency: "USD",
        image_url: "https://example.com/door-window-repair.jpg",
      },
      {
        service_id: "202",
        service_name: "Deck and Patio Construction",
        description: "Construction and repair of decks and patios.",
        price: 300,
        currency: "USD",
        image_url: "https://example.com/deck-patio-construction.jpg",
      },
      {
        service_id: "203",
        service_name: "Shelving and Storage",
        description: "Installation of shelves and storage solutions.",
        price: 70,
        currency: "USD",
        image_url: "https://example.com/shelving-storage.jpg",
      },
      {
        service_id: "301",
        service_name: "Framing",
        description: "Framing for walls and structures.",
        price: 120,
        currency: "USD",
        image_url: "https://example.com/framing.jpg",
      },
      {
        service_id: "302",
        service_name: "Wooden Flooring",
        description: "Installation and repair of wooden flooring.",
        price: 180,
        currency: "USD",
        image_url: "https://example.com/wooden-flooring.jpg",
      },
      {
        service_id: "303",
        service_name: "Staircase Design and Repair",
        description: "Design and repair of staircases.",
        price: 250,
        currency: "USD",
        image_url: "https://example.com/staircase-design-repair.jpg",
      },
    ],
  };
  