export let CarpenterServices = {
  service_id: "13",
  service_name: "Carpenter Services",
  description: "Expert carpentry services for all your woodworking needs.",
  service_categories: [
    {
      service_id: 101,
      service_name: "Furniture Repair",
      description: "Repair and restoration of furniture.",
      price: 80,
      currency: "USD",
      image_url: "https://media.istockphoto.com/id/1292302301/photo/craftsman-reupholstering-chair-in-workshop.jpg?s=612x612&w=0&k=20&c=K1HBPNVgsSpA674V3kYfWYGVeXDCfmkOy0A8HqhaECc=",
    },
    {
      service_id: 102,
      service_name: "Custom Furniture",
      description: "Creation of custom-made furniture.",
      price: 200,
      currency: "USD",
      image_url: "https://media.architecturaldigest.com/photos/5b6b45846f48c85479ae400c/16:9/w_2560%2Cc_limit/calivintage_campaignpillows.jpg",
    },
    {
      service_id: 103,
      service_name: "Cabinetry",
      description: "Design and installation of cabinets.",
      price: 150,
      currency: "USD",
      image_url: "https://media.gettyimages.com/id/1254400064/photo/domestic-kitchen.jpg?s=612x612&w=gi&k=20&c=m-iQdMY6g2DqX7eJ7NwUrwQ3RYOYVzvMs9jpuy3qdeg=",
    },
    {
      service_id: 104,
      service_name: "Door and Window Repair",
      description: "Repair and installation of doors and windows.",
      price: 100,
      currency: "USD",
      image_url: "https://cdn.mrright.in/cdn/content/assets/2015-11/small/de37da3bcfc34f9b8af34badfdc0dee2-door%20or%20window%20repair%20.jpg?sv=2020-04-08&si=MrRightCDNAccessPolicy&sr=c&sig=%2B6fs9xgu5wLh9HEJ0lNaoOt8HIH6CHQYpw5F0vISsdk%3D",
    },
    {
      service_id: 105,
      service_name: "Deck and Patio Construction",
      description: "Construction and repair of decks and patios.",
      price: 300,
      currency: "USD",
      image_url: "https://east-coast-renovations.com/wp-content/uploads/2016/02/Deck-and-Patio-Construction.jpg",
    },
    {
      service_id: 106,
      service_name: "Shelving and Storage",
      description: "Installation of shelves and storage solutions.",
      price: 70,
      currency: "USD",
      image_url: "https://www.ana-white.com/sites/default/files/diy%20garage%20shelving04_0.jpg",
    },
    {
      service_id: 107,
      service_name: "Framing",
      description: "Framing for walls and structures.",
      price: 120,
      currency: "USD",
      image_url: "https://www.buildmyowncabin.com/framing/standing-wall.jpg",
    },
    {
      service_id: 108,
      service_name: "Wooden Flooring",
      description: "Installation and repair of wooden flooring.",
      price: 180,
      currency: "USD",
      image_url: "https://5.imimg.com/data5/KR/LL/WE/SELLER-70874002/wooden-flooring.jpg",
    },
    {
      service_id: 109,
      service_name: "Staircase Design and Repair",
      description: "Design and repair of staircases.",
      price: 250,
      currency: "USD",
      image_url: "https://s42814.pcdn.co/wp-content/uploads/2020/08/iStock_1047941552-1-scaled.jpg.optimal.jpg",
    },
    // Continue adding more services with unique IDs (e.g., 110, 111, etc.)
  ],
};

console.log(CarpenterServices);
