export  let ElectronicItems = {
  service_id: "3",
  service_name: "Electronic Items",
  description: "Professional electronic items services for repair and maintenance.",
  service_categories: [
    {
      service_id: "101",
      service_name: "TV Repair",
      price: 80,
      currency: "USD",
      category_name: "Television",
    },
    {
      service_id: "102",
      service_name: "Laptop Repair",
      price: 100,
      currency: "USD",
      category_name: "Computers",
    },
    {
      service_id: "103",
      service_name: "Smartphone Repair",
      price: 50,
      currency: "USD",
      category_name: "Mobile Devices",
    },
    {
      service_id: "201",
      service_name: "Camera Repair",
      price: 70,
      currency: "USD",
      category_name: "Photography",
    },
    {
      service_id: "202",
      service_name: "Printer Repair",
      price: 60,
      currency: "USD",
      category_name: "Printers",
    },
    {
      service_id: "203",
      service_name: "Game Console Repair",
      price: 90,
      currency: "USD",
      category_name: "Gaming Consoles",
    },
    {
      service_id: "301",
      service_name: "Home Audio System Repair",
      price: 120,
      currency: "USD",
      category_name: "Audio Systems",
    },
    {
      service_id: "302",
      service_name: "Smart Home Device Setup",
      price: 40,
      currency: "USD",
      category_name: "Smart Home Devices",
    },
    {
      service_id: "303",
      service_name: "Appliance Repair",
      price: 70,
      currency: "USD",
      category_name: "Home Appliances",
    },
  ],
};
