export let ElectronicItems = {
  service_id: "3",
  service_name: "Electronic Items",
  description: "Professional electronic items services for repair and maintenance.",
  service_categories: [
    {
      service_id: 120,
      service_name: "TV Repair",
      description: "Expert TV repair service at affordable prices.",
      price: 80,
      currency: "USD",
      category_name: "Television",
      image_url: "https://5.imimg.com/data5/SELLER/Default/2022/11/AI/KK/FA/136653891/led-tv-repairing-services-500x500.jpg",
    },
    {
      service_id: 121,
      service_name: "Laptop Repair",
      description: "Professional laptop repair and troubleshooting.",
      price: 100,
      currency: "USD",
      category_name: "Computers",
      image_url: "https://img.freepik.com/premium-photo/computer-repair-laptop-concept-3d_441797-7358.jpg",
    },
    {
      service_id: 122,
      service_name: "Smartphone Repair",
      description: "Fast and reliable smartphone repair services.",
      price: 50,
      currency: "USD",
      category_name: "Mobile Devices",
      image_url: "https://media.istockphoto.com/id/512756266/photo/fixing-mobile-phone.jpg?s=612x612&w=0&k=20&c=Lgzw_qxkcqgOoPmI1LqQFA2LVtBVyj6kF5CoQXYpbfg=",
    },
    {
      service_id: 123,
      service_name: "Camera Repair",
      description: "Expert camera repair for all major brands.",
      price: 70,
      currency: "USD",
      category_name: "Photography",
      image_url: "https://kprabhakar.in/images/cam.png",
    },
    {
      service_id: 124,
      service_name: "Printer Repair",
      description: "Quality printer repair service for all types.",
      price: 60,
      currency: "USD",
      category_name: "Printers",
      image_url: "https://5.imimg.com/data5/OG/OV/MY-2685611/printer-service-500x500.jpg",
    },
    {
      service_id: 125,
      service_name: "Game Console Repair",
      description: "Expert repair for gaming consoles of all brands.",
      price: 90,
      currency: "USD",
      category_name: "Gaming Consoles",
      image_url: "https://content.jdmagicbox.com/comp/def_content/gaming-console-repair-and-services-xbox/gaming-console-repair---services-xbox-1-gaming-console-repair-and-services-xbox-1-38dp6.jpg?clr=#661a00?fit=around%7C270%3A130&crop=270%3A130%3B%2A%2C%2A",
    },
    {
      service_id: 126,
      service_name: "Home Audio System Repair",
      description: "Quality repair for audio systems at competitive prices.",
      price: 120,
      currency: "USD",
      category_name: "Audio Systems",
      image_url: "https://images.squarespace-cdn.com/content/v1/5ac67d6be2ccd15441260769/1562972868459-5KA3EOVZ2ER8BBPYHSBI/speaker-system-repair-utah.jpg",
    },
    {
      service_id: 127,
      service_name: "Smart Home Device Setup",
      description: "Professional setup for smart home devices.",
      price: 40,
      currency: "USD",
      category_name: "Smart Home Devices",
      image_url: "https://tufftechies.com/wp-content/uploads/2020/03/tuff-techies-smart-home-smart-device-setup-1-smaller.jpg",
    },
    {
      service_id: 128,
      service_name: "Appliance Repair",
      description: "Expert repair for all home appliances.",
      price: 70,
      currency: "USD",
      category_name: "Home Appliances",
      image_url: "https://texcial.com/wp-content/uploads/2021/05/sfffffffffffffffssssssss.jpg",
    },
  ],
};
