export let HomeCleaningServices = {
    service_id: "9",
    service_name: "Complete Home Cleaning",
    description: "Thorough and professional cleaning services to make your home sparkle.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Regular Cleaning",
        description: "General cleaning for all rooms, including dusting, vacuuming, and mopping.",
        price: 80,
        currency: "USD",
        image_url: "https://example.com/regular-cleaning.jpg",
      },
      {
        service_id: "102",
        service_name: "Deep Cleaning",
        description: "In-depth cleaning for hard-to-reach areas, including baseboards and fixtures.",
        price: 120,
        currency: "USD",
        image_url: "https://example.com/deep-cleaning.jpg",
      },
      {
        service_id: "103",
        service_name: "Kitchen Cleaning",
        description: "Thorough cleaning for the kitchen, including appliances and countertops.",
        price: 50,
        currency: "USD",
        image_url: "https://example.com/kitchen-cleaning.jpg",
      },
      {
        service_id: "201",
        service_name: "Bathroom Cleaning",
        description: "Sanitization and cleaning for bathrooms, including tiles and fixtures.",
        price: 40,
        currency: "USD",
        image_url: "https://example.com/bathroom-cleaning.jpg",
      },
      {
        service_id: "202",
        service_name: "Window Cleaning",
        description: "Cleaning of windows, glass surfaces, and window sills.",
        price: 60,
        currency: "USD",
        image_url: "https://example.com/window-cleaning.jpg",
      },
      {
        service_id: "203",
        service_name: "Carpet Cleaning",
        description: "Professional cleaning to remove dirt and stains from carpets.",
        price: 70,
        currency: "USD",
        image_url: "https://example.com/carpet-cleaning.jpg",
      },
      {
        service_id: "301",
        service_name: "Move-In/Move-Out Cleaning",
        description: "Thorough cleaning for a new or vacated home.",
        price: 150,
        currency: "USD",
        image_url: "https://example.com/move-in-out-cleaning.jpg",
      },
      {
        service_id: "302",
        service_name: "Pet-Friendly Cleaning",
        description: "Cleaning to remove pet hair and odors from the home.",
        price: 90,
        currency: "USD",
        image_url: "https://example.com/pet-friendly-cleaning.jpg",
      },
      {
        service_id: "303",
        service_name: "Green Cleaning",
        description: "Environmentally friendly cleaning using eco-friendly products.",
        price: 100,
        currency: "USD",
        image_url: "https://example.com/green-cleaning.jpg",
      },
    ],
  };
  