export let HousePaintingServices = {
    service_id: "12",
    service_name: "House Painting",
    description: "Professional house painting services to refresh and beautify your home.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Interior Painting",
        description: "Painting of the interior walls and ceilings.",
        price: 300,
        currency: "USD",
        image_url: "https://example.com/interior-painting.jpg",
      },
      {
        service_id: "102",
        service_name: "Exterior Painting",
        description: "Painting of the exterior walls and surfaces.",
        price: 500,
        currency: "USD",
        image_url: "https://example.com/exterior-painting.jpg",
      },
      {
        service_id: "103",
        service_name: "Trim and Accent Painting",
        description: "Painting of trims, doors, and accent walls.",
        price: 100,
        currency: "USD",
        image_url: "https://example.com/trim-accent-painting.jpg",
      },
      {
        service_id: "201",
        service_name: "Deck and Fence Staining",
        description: "Staining and sealing of decks and fences.",
        price: 200,
        currency: "USD",
        image_url: "https://example.com/deck-fence-staining.jpg",
      },
      {
        service_id: "202",
        service_name: "Cabinet Refinishing",
        description: "Refinishing and painting of kitchen cabinets.",
        price: 250,
        currency: "USD",
        image_url: "https://example.com/cabinet-refinishing.jpg",
      },
      {
        service_id: "203",
        service_name: "Wallpaper Removal",
        description: "Removal of old wallpaper from walls.",
        price: 80,
        currency: "USD",
        image_url: "https://example.com/wallpaper-removal.jpg",
      },
      {
        service_id: "301",
        service_name: "Color Consultation",
        description: "Professional consultation for choosing the perfect colors.",
        price: 50,
        currency: "USD",
        image_url: "https://example.com/color-consultation.jpg",
      },
      {
        service_id: "302",
        service_name: "Drywall Repair",
        description: "Repair of drywall imperfections and damages.",
        price: 120,
        currency: "USD",
        image_url: "https://example.com/drywall-repair.jpg",
      },
      {
        service_id: "303",
        service_name: "Texture Application",
        description: "Application of textured finishes to walls.",
        price: 90,
        currency: "USD",
        image_url: "https://example.com/texture-application.jpg",
      },
    ],
  };
  