export let LaundryServices = {
    service_id: "8",
    service_name: "Laundry Services",
    description: "Efficient laundry services to keep your clothes clean and fresh.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Wash & Fold",
        price: 15,
        currency: "USD",
        category_name: "Regular Laundry",
        image_url: "https://example.com/wash-fold.jpg",
      },
      {
        service_id: "102",
        service_name: "Dry Cleaning",
        price: 25,
        currency: "USD",
        category_name: "Specialty Cleaning",
        image_url: "https://example.com/dry-cleaning.jpg",
      },
      {
        service_id: "103",
        service_name: "Ironing",
        price: 10,
        currency: "USD",
        category_name: "Ironing Services",
        image_url: "https://example.com/ironing.jpg",
      },
      {
        service_id: "201",
        service_name: "Bedding & Linen",
        price: 20,
        currency: "USD",
        category_name: "Bulk Laundry",
        image_url: "https://example.com/bedding-linen.jpg",
      },
      {
        service_id: "202",
        service_name: "Clothing Alterations",
        price: 15,
        currency: "USD",
        category_name: "Alterations",
        image_url: "https://example.com/clothing-alterations.jpg",
      },
      {
        service_id: "203",
        service_name: "Stain Removal",
        price: 12,
        currency: "USD",
        category_name: "Specialty Cleaning",
        image_url: "https://example.com/stain-removal.jpg",
      },
      {
        service_id: "301",
        service_name: "Express Service",
        price: 5,
        currency: "USD",
        category_name: "Priority Service",
        image_url: "https://example.com/express-service.jpg",
      },
      {
        service_id: "302",
        service_name: "Pickup & Delivery",
        price: 8,
        currency: "USD",
        category_name: "Convenience Services",
        image_url: "https://example.com/pickup-delivery.jpg",
      },
      {
        service_id: "303",
        service_name: "Eco-Friendly Cleaning",
        price: 18,
        currency: "USD",
        category_name: "Environmentally Friendly",
        image_url: "https://example.com/eco-friendly-cleaning.jpg",
      },
    ],
  };
  