export let MassageCare = {
    service_id: "7",
    service_name: "Massage Care",
    description: "Relax and rejuvenate with our soothing massage treatments.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Swedish Massage",
        price: 60,
        currency: "USD",
        category_name: "Massage",
        image_url: "https://example.com/swedish-massage.jpg",
      },
      {
        service_id: "102",
        service_name: "Deep Tissue Massage",
        price: 70,
        currency: "USD",
        category_name: "Massage",
        image_url: "https://example.com/deep-tissue-massage.jpg",
      },
      {
        service_id: "103",
        service_name: "Hot Stone Massage",
        price: 80,
        currency: "USD",
        category_name: "Massage",
        image_url: "https://example.com/hot-stone-massage.jpg",
      },
      {
        service_id: "201",
        service_name: "Aromatherapy Massage",
        price: 65,
        currency: "USD",
        category_name: "Massage",
        image_url: "https://example.com/aromatherapy-massage.jpg",
      },
      {
        service_id: "202",
        service_name: "Thai Massage",
        price: 75,
        currency: "USD",
        category_name: "Massage",
        image_url: "https://example.com/thai-massage.jpg",
      },
      {
        service_id: "203",
        service_name: "Sports Massage",
        price: 70,
        currency: "USD",
        category_name: "Massage",
        image_url: "https://example.com/sports-massage.jpg",
      },
      {
        service_id: "301",
        service_name: "Prenatal Massage",
        price: 55,
        currency: "USD",
        category_name: "Specialty Massage",
        image_url: "https://example.com/prenatal-massage.jpg",
      },
      {
        service_id: "302",
        service_name: "Couples Massage",
        price: 130,
        currency: "USD",
        category_name: "Specialty Massage",
        image_url: "https://example.com/couples-massage.jpg",
      },
      {
        service_id: "303",
        service_name: "Reflexology",
        price: 45,
        currency: "USD",
        category_name: "Specialty Massage",
        image_url: "https://example.com/reflexology.jpg",
      },
    ],
  };
  