export let MechanicServices = {
    service_id: "11",
    service_name: "Mechanic Services",
    description: "Expert automotive mechanic services to keep your vehicle running smoothly.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Oil Change",
        description: "Regular oil change to maintain engine performance.",
        price: 40,
        currency: "USD",
        image_url: "https://example.com/oil-change.jpg",
      },
      {
        service_id: "102",
        service_name: "Brake Inspection and Repair",
        description: "Inspection and repair of brake system for safety.",
        price: 80,
        currency: "USD",
        image_url: "https://example.com/brake-inspection-repair.jpg",
      },
      {
        service_id: "103",
        service_name: "Tire Replacement",
        description: "Replacement of old or damaged tires with new ones.",
        price: 120,
        currency: "USD",
        image_url: "https://example.com/tire-replacement.jpg",
      },
      {
        service_id: "201",
        service_name: "Engine Diagnostics",
        description: "Advanced diagnostics to identify engine issues.",
        price: 60,
        currency: "USD",
        image_url: "https://example.com/engine-diagnostics.jpg",
      },
      {
        service_id: "202",
        service_name: "Battery Replacement",
        description: "Replacement of old or faulty batteries.",
        price: 100,
        currency: "USD",
        image_url: "https://example.com/battery-replacement.jpg",
      },
      {
        service_id: "203",
        service_name: "Air Conditioning Service",
        description: "Service and repair of the vehicle's air conditioning system.",
        price: 70,
        currency: "USD",
        image_url: "https://example.com/air-conditioning-service.jpg",
      },
      {
        service_id: "301",
        service_name: "Transmission Repair",
        description: "Expert repair of the vehicle's transmission system.",
        price: 150,
        currency: "USD",
        image_url: "https://example.com/transmission-repair.jpg",
      },
      {
        service_id: "302",
        service_name: "Suspension and Steering",
        description: "Inspection and repair of suspension and steering components.",
        price: 90,
        currency: "USD",
        image_url: "https://example.com/suspension-steering.jpg",
      },
      {
        service_id: "303",
        service_name: "Exhaust System Repair",
        description: "Repair and replacement of the vehicle's exhaust system.",
        price: 110,
        currency: "USD",
        image_url: "https://example.com/exhaust-system-repair.jpg",
      },
    ],
  };
  