export let PestControlServices = {
    service_id: "10",
    service_name: "Pest Control",
    description: "Effective pest control services to keep your home free from pests and insects.",
    service_categories: [
      {
        service_id: "101",
        service_name: "General Pest Control",
        description: "Treatment for common pests like ants, cockroaches, and spiders.",
        price: 80,
        currency: "USD",
        image_url: "https://example.com/general-pest-control.jpg",
      },
      {
        service_id: "102",
        service_name: "Rodent Control",
        description: "Elimination of mice, rats, and other rodents from your property.",
        price: 120,
        currency: "USD",
        image_url: "https://example.com/rodent-control.jpg",
      },
      {
        service_id: "103",
        service_name: "Termite Control",
        description: "Specialized treatment to eradicate termites and protect your home.",
        price: 150,
        currency: "USD",
        image_url: "https://example.com/termite-control.jpg",
      },
      {
        service_id: "201",
        service_name: "Bed Bug Extermination",
        description: "Thorough removal of bed bugs from mattresses and furniture.",
        price: 100,
        currency: "USD",
        image_url: "https://example.com/bed-bug-extermination.jpg",
      },
      {
        service_id: "202",
        service_name: "Mosquito Control",
        description: "Effective control of mosquitoes to reduce the risk of diseases.",
        price: 60,
        currency: "USD",
        image_url: "https://example.com/mosquito-control.jpg",
      },
      {
        service_id: "203",
        service_name: "Wasp and Bee Removal",
        description: "Safe removal of wasp nests and beehives from your property.",
        price: 70,
        currency: "USD",
        image_url: "https://example.com/wasp-bee-removal.jpg",
      },
      {
        service_id: "301",
        service_name: "Flea and Tick Treatment",
        description: "Elimination of fleas and ticks from your home and pets.",
        price: 80,
        currency: "USD",
        image_url: "https://example.com/flea-tick-treatment.jpg",
      },
      {
        service_id: "302",
        service_name: "Bird Control",
        description: "Deterrence and removal of birds from nesting in unwanted areas.",
        price: 90,
        currency: "USD",
        image_url: "https://example.com/bird-control.jpg",
      },
      {
        service_id: "303",
        service_name: "Mole and Vole Control",
        description: "Control of moles and voles damaging your lawn and garden.",
        price: 85,
        currency: "USD",
        image_url: "https://example.com/mole-vole-control.jpg",
      },
    ],
  };
  