export let WomensSalon = {
  service_id: "4",
  service_name: "Hair Salon",
  description: "Expert hair care services in a relaxing and friendly atmosphere.",
  service_categories: [
    {
      service_id: 380,
      service_name: "Haircut",
      description: "Professional haircuts to enhance your style.",
      price: 30,
      currency: "USD",
      category_name: "Haircuts",
      image_url: "https://img.freepik.com/premium-photo/young-man-with-trendy-haircut-barber-shop-barber-does-hairstyle-beard-trim_179755-8607.jpg",
    },
    {
      service_id: 381,
      service_name: "Hair Color",
      description: "Hair coloring for a fresh and vibrant look.",
      price: 70,
      currency: "USD",
      category_name: "Hair Color",
      image_url: "https://sinimangatt.com/cdn/shop/articles/Balayage_Hair_Coloring_at_Sinima_Salon_1800x.png?v=1606385054",
    },
    {
      service_id: 382,
      service_name: "Highlights",
      description: "Adding highlights to add dimension to your hair.",
      price: 80,
      currency: "USD",
      category_name: "Hair Color",
      image_url: "https://files.myglamm.com/site-images/original/Into-The-Blue-highlights.png",
    },
    {
      service_id: 383,
      service_name: "Facial",
      description: "Rejuvenating facials for glowing and healthy skin.",
      price: 50,
      currency: "USD",
      category_name: "Facials",
      image_url: "https://images.squarespace-cdn.com/content/v1/5d6b3013248be40001de4764/1567588578206-MZRQS3F3PRZJ9AZA2103/get-a-facial.png",
    },
    {
      service_id: 384,
      service_name: "Chemical Peel",
      description: "Chemical peels to improve skin texture and appearance.",
      price: 100,
      currency: "USD",
      category_name: "Facials",
      image_url: "https://www.skinvitality.ca/wp-content/uploads/2021/06/Glycolic-peel-before-and-after-6.jpg.webp",
    },
    {
      service_id: 385,
      service_name: "Microdermabrasion",
      description: "Microdermabrasion for smoother and brighter skin.",
      price: 120,
      currency: "USD",
      category_name: "Facials",
      image_url: "https://myskinph.com/wp-content/uploads/2019/03/Microdermabrasion-vs-Chemical-Peel.jpg",
    },
    {
      service_id: 386,
      service_name: "Manicure",
      description: "Professional manicures for well-groomed nails.",
      price: 25,
      currency: "USD",
      category_name: "Nails",
      image_url: "https://hips.hearstapps.com/hmg-prod/images/manicure-1623875537.png?crop=0.502xw:1.00xh;0.0867xw,0&resize=1200:*",
    },
    {
      service_id: 387,
      service_name: "Pedicure",
      description: "Relaxing pedicures to pamper your feet.",
      price: 30,
      currency: "USD",
      category_name: "Nails",
      image_url: "https://naturatermospa.com/wp-content/uploads/2019/10/image-95.jpeg",
    },
    {
      service_id: 388,
      service_name: "Gel Nail Extensions",
      description: "Stylish gel nail extensions for longer-lasting nails.",
      price: 50,
      currency: "USD",
      category_name: "Nails",
      image_url: "https://www.glamnails.in/wp-content/uploads/2022/05/3-1.jpg",
    },
  ],
};
