export let WomensSalon = {
    service_id: "6",
    service_name: "Women's Salon",
    description: "Pamper yourself with our luxurious women's salon services.",
    service_categories: [
      {
        service_id: "101",
        service_name: "Haircut",
        price: 40,
        currency: "USD",
        category_name: "Haircuts",
        image_url: "https://example.com/haircut.jpg",
      },
      {
        service_id: "102",
        service_name: "Hair Styling",
        price: 50,
        currency: "USD",
        category_name: "Haircuts",
        image_url: "https://example.com/hair-styling.jpg",
      },
      {
        service_id: "103",
        service_name: "Hair Color",
        price: 80,
        currency: "USD",
        category_name: "Hair Color",
        image_url: "https://example.com/hair-color.jpg",
      },
      {
        service_id: "201",
        service_name: "Manicure",
        price: 25,
        currency: "USD",
        category_name: "Nails",
        image_url: "https://example.com/manicure.jpg",
      },
      {
        service_id: "202",
        service_name: "Pedicure",
        price: 30,
        currency: "USD",
        category_name: "Nails",
        image_url: "https://example.com/pedicure.jpg",
      },
      {
        service_id: "203",
        service_name: "Nail Art",
        price: 40,
        currency: "USD",
        category_name: "Nails",
        image_url: "https://example.com/nail-art.jpg",
      },
      {
        service_id: "301",
        service_name: "Facial",
        price: 60,
        currency: "USD",
        category_name: "Skin Treatments",
        image_url: "https://example.com/facial.jpg",
      },
      {
        service_id: "302",
        service_name: "Waxing",
        price: 45,
        currency: "USD",
        category_name: "Skin Treatments",
        image_url: "https://example.com/waxing.jpg",
      },
      {
        service_id: "303",
        service_name: "Eyebrow Threading",
        price: 20,
        currency: "USD",
        category_name: "Skin Treatments",
        image_url: "https://example.com/eyebrow-threading.jpg",
      },
    ],
  };
  